version: "3"
x-common-variables: &common-variables
  PORT: 5050
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_DATABASE: ${POSTGRES_DATABASE}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: ${POSTGRES_PORT}

services:
  postgres:
    container_name: postgres-container
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: *common-variables
  
  api:
    container_name: api-container
    restart: always
    build: .
    volumes:
      - ./package.json:/workspace/clean-node-api/package.json
      - ./dist:/workspace/clean-node-api/dist
    ports:
      - "5050:5050"
      - "9222:9222"
    command: npm run debug
    links:
      - postgres
