version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.4
    restart: always
    volumes:
      - ./docker/mongo:/data/db
    ports:
      - "27017:27017"

  postgres:
    container_name: postgres-container
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clean-node-api
      - POSTGRES_PASSWORD=root
  
  api:
    container_name: api-container
    restart: always
    build: .
    volumes:
      - ./dist:/workspace/clean-node-api/dist
    ports:
      - "5050:5050"
    command: npm start
    links:
      - mongo
      - postgres
